default: &default
    adapter: postgresql
    encoding: unicode
    username: admin
    password: team4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: rmc_development_db

test:
  <<: *default
  host: localhost
  database: rmc_test_db

production:
  <<: *default
  database: rmc_db